import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import Script from "next/script"; // Import Script from Next.js
import "./globals.css";
import { Navigation } from "@/components/navigation";
import { Footer } from "@/components/footer";
import { Chatbot } from "@/components/chatbot";
import { AuthProvider } from "@/contexts/AuthContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { SITE, buildMetadata, travelAgencyLd, websiteLd } from "@/lib/seo";
import { JsonLd } from "@/components/seo/json-ld";
import { PublicOnly } from "@/components/public-only";

const inter = Inter({ subsets: ["latin"] });

// Mobile viewport + browser-chrome theme colour (mobile-first).
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  themeColor: "#f45201",
};

export const metadata: Metadata = {
  metadataBase: new URL(SITE.url),
  title: {
    default: SITE.defaultTitle,
    template: SITE.titleTemplate,
  },
  applicationName: SITE.name,
  authors: [{ name: SITE.name, url: SITE.url }],
  creator: SITE.name,
  publisher: SITE.name,
  category: "travel",
  // Home-page canonical, keywords, robots, OpenGraph and Twitter cards.
  ...buildMetadata({ path: "/" }),
  // Icons are auto-generated by Next.js from app/favicon.ico, app/icon.png
  // and app/apple-icon.png — no manual config needed.
  manifest: "/manifest.webmanifest",
  verification: {
    google: "google1dc4d70f7f78498c",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Razorpay Checkout Script */}
        <Script
          src="https://checkout.razorpay.com/v1/checkout.js"
          strategy="beforeInteractive"
        />
      </head>
      <body className={inter.className} style={{ backgroundColor: "#f9f7da" }}>
        {/* Site-wide structured data: business entity + website */}
        <JsonLd data={[travelAgencyLd(), websiteLd()]} />
        <AuthProvider>
          <PublicOnly>
            <Navigation />
          </PublicOnly>
          <main>{children}</main>
          <PublicOnly>
            <Chatbot />
            <Footer />
          </PublicOnly>
          <ToastContainer />
        </AuthProvider>
      </body>
    </html>
  );
}
